FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY .env .
COPY config/ ./config/
COPY client/ ./client/
COPY cert/ ./cert/

CMD ["python", "-m", "client.main"]